# Pizza Place Analysis

## The data was gathered from Kaggel 

## Tools Python, Pandas, Sql and Power Bi

### This project is about Pizza place. It contains data about orders, pizza names, sizes, quantity and price. Will be analysing about - 
### Which was the best / worst pizza sold? 
### Which category and size are most popular?
### How can shop improve its sales?

In [13]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import seaborn as sns

In [2]:
df_orders = pd.read_csv("../Data/orders.csv")

In [3]:
df_order_details = pd.read_csv("../Data/order_details.csv")

In [4]:
df_pizza_types = pd.read_csv("../Data/pizza_types.csv", encoding="cp1252")

In [5]:
df_pizza = pd.read_csv("../Data/pizzas.csv")

In [13]:
df_orders.head()

   order_id        date      time
0         1  2015-01-01  11:38:36
1         2  2015-01-01  11:57:40
2         3  2015-01-01  12:12:28
3         4  2015-01-01  12:16:31
4         5  2015-01-01  12:21:30

In [15]:
df_order_details.head()

   order_details_id  order_id       pizza_id  quantity
0                 1         1     hawaiian_m         1
1                 2         2  classic_dlx_m         1
2                 3         2  five_cheese_l         1
3                 4         2    ital_supr_l         1
4                 5         2     mexicana_m         1

In [16]:
df_pizza.head()

     pizza_id pizza_type_id size  price
0   bbq_ckn_s       bbq_ckn    S  12.75
1   bbq_ckn_m       bbq_ckn    M  16.75
2   bbq_ckn_l       bbq_ckn    L  20.75
3  cali_ckn_s      cali_ckn    S  12.75
4  cali_ckn_m      cali_ckn    M  16.75

In [17]:
df_pizza_types.head()

,pizza_type_id,name,category,ingredients
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,..."
1,cali_ckn,The California Chicken Pizza,Chicken,"Chicken, Artichoke, Spinach, Garlic, Jalapeno ..."
2,ckn_alfredo,The Chicken Alfredo Pizza,Chicken,"Chicken, Red Onions, Red Peppers, Mushrooms, A..."
3,ckn_pesto,The Chicken Pesto Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Spinach, Garli..."
4,southw_ckn,The Southwest Chicken Pizza,Chicken,"Chicken, Tomatoes, Red Peppers, Red Onions, Ja..."

In [28]:
df_order_details.shape

(48620, 4)

In [29]:
df_orders.shape

(21350, 3)

In [30]:
df_pizza.shape

(96, 4)

In [31]:
df_pizza_types.shape

(32, 4)

In [34]:
df_order_details.columns

Index(['order_details_id', 'order_id', 'pizza_id', 'quantity'], dtype='object')

In [35]:
df_orders.columns

Index(['order_id', 'date', 'time'], dtype='object')

In [36]:
df_pizza.columns

Index(['pizza_id', 'pizza_type_id', 'size', 'price'], dtype='object')

In [37]:
df_pizza_types.columns

Index(['pizza_type_id', 'name', 'category', 'ingredients'], dtype='object')

In [20]:
df_order_details.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 48620 entries, 0 to 48619
Data columns (total 4 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   order_details_id  48620 non-null  int64
 1   order_id          48620 non-null  int64
 2   pizza_id          48620 non-null  object
 3   quantity          48620 non-null  int64
dtypes: int64(3), object(1)
memory usage: 1.5+ MB

In [21]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  21350 non-null  int64
 1   date      21350 non-null  object
 2   time      21350 non-null  object
dtypes: int64(1), object(2)
memory usage: 500.5+ KB

In [22]:
df_pizza.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96 entries, 0 to 95
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_id       96 non-null     object
 1   pizza_type_id  96 non-null     object
 2   size           96 non-null     object
 3   price          96 non-null     float64
dtypes: float64(1), object(3)
memory usage: 3.1+ KB

In [23]:
df_pizza_types.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 32 entries, 0 to 31
Data columns (total 4 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   pizza_type_id  32 non-null     object
 1   name           32 non-null     object
 2   category       32 non-null     object
 3   ingredients    32 non-null     object
dtypes: object(4)
memory usage: 1.1+ KB

In [24]:
df_order_details.isnull().sum()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
dtype: int64

In [64]:
df_order_details.isna().sum()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
dtype: int64

In [25]:
df_orders.isnull().sum()

order_id    0
date        0
time        0
dtype: int64

In [65]:
df_orders.isna().sum()

order_id    0
date        0
time        0
dtype: int64

In [26]:
df_pizza.isnull().sum()

pizza_id         0
pizza_type_id    0
size             0
price            0
dtype: int64

In [66]:
df_pizza.isna().sum()

pizza_id         0
pizza_type_id    0
size             0
price            0
dtype: int64

In [27]:
df_pizza_types.isnull().sum()

pizza_type_id    0
name             0
category         0
ingredients      0
dtype: int64

In [67]:
df_pizza_types.isna().sum()

pizza_type_id    0
name             0
category         0
ingredients      0
dtype: int64

In [9]:
df_orders["date"] = pd.to_datetime(df_orders["date"])

In [25]:
df_orders["time"] = pd.to_datetime(df_orders["time"], format = "%H:%M:%S")

In [26]:
df_orders["time"] = df_orders["time"].dt.time

In [27]:
df_orders.head()

   order_id       date      time
0         1 2015-01-01  11:38:36
1         2 2015-01-01  11:57:40
2         3 2015-01-01  12:12:28
3         4 2015-01-01  12:16:31
4         5 2015-01-01  12:21:30

In [28]:
df_orders.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21350 entries, 0 to 21349
Data columns (total 3 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   order_id  21350 non-null  int64
 1   date      21350 non-null  datetime64[ns]
 2   time      21350 non-null  object
dtypes: datetime64[ns](1), int64(1), object(1)
memory usage: 500.5+ KB

In [44]:
df_order_details.duplicated().sum()

np.int64(0)

In [45]:
df_orders.duplicated().sum()

np.int64(0)

In [46]:
df_pizza.duplicated().sum()

np.int64(0)

In [47]:
df_pizza_types.duplicated().sum()

np.int64(0)

In [49]:
df_order_details.describe()

       order_details_id      order_id      quantity
count      48620.000000  48620.000000  48620.000000
mean       24310.500000  10701.479761      1.019622
std        14035.529381   6180.119770      0.143077
min            1.000000      1.000000      1.000000
25%        12155.750000   5337.000000      1.000000
50%        24310.500000  10682.500000      1.000000
75%        36465.250000  16100.000000      1.000000
max        48620.000000  21350.000000      4.000000

In [50]:
df_orders.describe()

,order_id,date,time
count,21350.000000,21350,21350
mean,10675.500000,2015-06-28 23:41:47.353630208,1900-01-01 16:35:03.895503616
min,1.000000,2015-01-01 00:00:00,1900-01-01 09:52:21
25%,5338.250000,2015-03-31 00:00:00,1900-01-01 13:35:05
50%,10675.500000,2015-06-28 00:00:00,1900-01-01 16:48:53.500000
75%,16012.750000,2015-09-27 00:00:00,1900-01-01 19:05:08.750000128
max,21350.000000,2015-12-31 00:00:00,1900-01-01 23:05:52
std,6163.358459,NaN,NaN

In [51]:
df_pizza.describe()

           price
count  96.000000
mean   16.440625
std     4.090266
min     9.750000
25%    12.500000
50%    16.250000
75%    20.250000
max    35.950000

In [52]:
df_pizza_types.describe()

,pizza_type_id,name,category,ingredients
count,32,32,32,32
unique,32,32,4,32
top,bbq_ckn,The Barbecue Chicken Pizza,Veggie,"Barbecued Chicken, Red Peppers, Green Peppers,..."
freq,1,1,9,1

In [41]:
df_pizza_types['pizza_type_id'].unique()

array(['bbq_ckn', 'cali_ckn', 'ckn_alfredo', 'ckn_pesto', 'southw_ckn',
       'thai_ckn', 'big_meat', 'classic_dlx', 'hawaiian', 'ital_cpcllo',
       'napolitana', 'pep_msh_pep', 'pepperoni', 'the_greek',
       'brie_carre', 'calabrese', 'ital_supr', 'peppr_salami',
       'prsc_argla', 'sicilian', 'soppressata', 'spicy_ital',
       'spinach_supr', 'five_cheese', 'four_cheese', 'green_garden',
       'ital_veggie', 'mediterraneo', 'mexicana', 'spin_pesto',
       'spinach_fet', 'veggie_veg'], dtype=object)

In [40]:
df_order_details['quantity'].unique()

array([1, 2, 3, 4])

In [57]:
df_orders["order_id"].nunique()

21350

In [58]:
df_order_details["order_details_id"].nunique()

48620

In [60]:
df_pizza["pizza_id"].nunique()

96

In [61]:
df_pizza_types["pizza_type_id"].nunique()

32

### Order_id in df_order_details exist in df_orders

In [68]:
Matching_OrderIds = df_order_details[
    df_order_details["order_id"].isin(df_orders["order_id"])
]

print("Matching Order Ids:", len(Matching_OrderIds))

Matching Order Ids: 48620

In [67]:
Missing_OrderIds = df_order_details[
    ~ df_order_details["order_id"].isin(df_orders["order_id"])
]

print("Missing Order Ids:", len(Missing_OrderIds))

Missing Order Ids: 0

### Pizza_id in df_order_details exist in df_pizzas

In [72]:
Matching_PizzaIds = df_order_details[
    df_order_details["pizza_id"].isin(df_pizza["pizza_id"])
]

print("Matching Pizza Ids:", len(Matching_PizzaIds))

Matching Pizza Ids: 48620

In [70]:
Missing_PizzaIds = df_order_details[
    ~ df_order_details["pizza_id"].isin(df_pizza["pizza_id"])
]

print("Missing Pizza Ids:", len(Missing_PizzaIds))

Missing Pizza Ids: 0

### Pizza_type_id in df_pizzas exist in df_pizza_types

In [73]:
Matching_Pizza_TypeIds = df_pizza[
    df_pizza["pizza_type_id"].isin(df_pizza_types["pizza_type_id"])
]

print("Matching Pizza Types Ids:", len(Matching_Pizza_TypeIds))

Matching Pizza Types Ids: 96

In [74]:
Missing_Pizza_TypeIds = df_pizza[
    ~ df_pizza["pizza_type_id"].isin(df_pizza_types["pizza_type_id"])
]

print("Missing Pizza Types Ids:", len(Missing_Pizza_TypeIds))

Missing Pizza Types Ids: 0

In [83]:
df_orders[df_orders["date"].dt.year != 2015].count()

order_id    0
date        0
time        0
dtype: int64

In [97]:
df_orders["time"].head()

0   1900-01-01 11:38:36
1   1900-01-01 11:57:40
2   1900-01-01 12:12:28
3   1900-01-01 12:16:31
4   1900-01-01 12:21:30
Name: time, dtype: datetime64[ns]

In [30]:
df_orders["time"].max()

datetime.time(23, 5, 52)

In [31]:
df_orders["time"].min()

datetime.time(9, 52, 21)

In [35]:
df_orders["time"].between(
    df_orders["time"].min(),
    df_orders["time"].max()
).sum()

np.int64(21350)

In [36]:
from datetime import time

df_orders["time"].between(
    time(9, 52, 21),
    time(23, 5, 52)
).sum()

np.int64(21350)

In [90]:
df_order_details[df_order_details["quantity"] <= 0].count()

order_details_id    0
order_id            0
pizza_id            0
quantity            0
dtype: int64

### Pizza categories generate the most revenue

In [72]:
df_pizza_orders = pd.merge(df_pizza, df_order_details, on="pizza_id", how="inner")

df_pizza_orders.head()

    pizza_id pizza_type_id size  price  order_details_id  order_id  quantity
0  bbq_ckn_s       bbq_ckn    S  12.75                11         6         1
1  bbq_ckn_s       bbq_ckn    S  12.75               239       102         1
2  bbq_ckn_s       bbq_ckn    S  12.75               294       124         1
3  bbq_ckn_s       bbq_ckn    S  12.75               458       194         1
4  bbq_ckn_s       bbq_ckn    S  12.75               489       208         1

In [73]:
df_pizza_orders.isnull().sum()

pizza_id            0
pizza_type_id       0
size                0
price               0
order_details_id    0
order_id            0
quantity            0
dtype: int64

In [74]:
df_pizza_orders.isna().sum()

pizza_id            0
pizza_type_id       0
size                0
price               0
order_details_id    0
order_id            0
quantity            0
dtype: int64

In [75]:
df_pizza_orders["Revenue"] =  df_pizza_orders["price"] * df_pizza_orders["quantity"]

df_pizza_orders.head()

,pizza_id,pizza_type_id,size,price,order_details_id,order_id,quantity,Revenue
0,bbq_ckn_s,bbq_ckn,S,12.75,11,6,1,12.75
1,bbq_ckn_s,bbq_ckn,S,12.75,239,102,1,12.75
2,bbq_ckn_s,bbq_ckn,S,12.75,294,124,1,12.75
3,bbq_ckn_s,bbq_ckn,S,12.75,458,194,1,12.75
4,bbq_ckn_s,bbq_ckn,S,12.75,489,208,1,12.75

In [76]:
Total_Revenue = df_pizza_orders["Revenue"].sum()
round(Total_Revenue, 2)

np.float64(817860.05)

### Revenue by pizza category

In [80]:
df_pizza_category = pd.merge(df_pizza_types, df_pizza_orders, on="pizza_type_id", how="outer")

df_pizza_category.head()

,pizza_type_id,name,category,ingredients,pizza_id,size,price,order_details_id,order_id,quantity,Revenue
0,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",bbq_ckn_s,S,12.75,11,6,1,12.75
1,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",bbq_ckn_s,S,12.75,239,102,1,12.75
2,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",bbq_ckn_s,S,12.75,294,124,1,12.75
3,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",bbq_ckn_s,S,12.75,458,194,1,12.75
4,bbq_ckn,The Barbecue Chicken Pizza,Chicken,"Barbecued Chicken, Red Peppers, Green Peppers,...",bbq_ckn_s,S,12.75,489,208,1,12.75

In [81]:
df_pizza_category.isnull().sum()

pizza_type_id       0
name                0
category            0
ingredients         0
pizza_id            0
size                0
price               0
order_details_id    0
order_id            0
quantity            0
Revenue             0
dtype: int64

In [82]:
df_pizza_category.isna().sum()

pizza_type_id       0
name                0
category            0
ingredients         0
pizza_id            0
size                0
price               0
order_details_id    0
order_id            0
quantity            0
Revenue             0
dtype: int64

In [85]:
Category_Revenue = df_pizza_category.groupby("category")["Revenue"].sum()
Category_Revenue

category
Chicken    195919.50
Classic    220053.10
Supreme    208197.00
Veggie     193690.45
Name: Revenue, dtype: float64

### Analyze sales volume

In [88]:
Sales_Volumes = df_pizza_category.groupby("category")["quantity"].sum()
Sales_Volumes

category
Chicken    11050
Classic    14888
Supreme    11987
Veggie     11649
Name: quantity, dtype: int64

### Average Selling Price

In [188]:
Average_Selling_Price = df_pizza["price"].mean()
Average_Selling_Price

np.float64(16.440625)

### Average selling price by category

In [175]:
Average_Selling_Price_Category = (
    df_pizza_category.groupby("category")["Revenue"].sum()
    / df_pizza_category.groupby("category")["quantity"].sum()
)

Average_Selling_Price_Category

category
Chicken    17.730271
Classic    14.780568
Supreme    17.368566
Veggie     16.627217
dtype: float64

### Top 5 pizza types by revenue

In [103]:
Top_5_Pizza = df_pizza_category.groupby("name")["Revenue"].sum().sort_values(ascending=False).head(5)
Top_5_Pizza

name
The Thai Chicken Pizza          43434.25
The Barbecue Chicken Pizza      42768.00
The California Chicken Pizza    41409.50
The Classic Deluxe Pizza        38180.50
The Spicy Italian Pizza         34831.25
Name: Revenue, dtype: float64

### Find the bottom 5 pizza types by revenue

In [105]:
Bottom_5_Pizza = df_pizza_category.groupby("name")["Revenue"].sum().sort_values().head(5)
Bottom_5_Pizza

name
The Brie Carre Pizza         11588.50
The Green Garden Pizza       13955.75
The Spinach Supreme Pizza    15277.75
The Mediterranean Pizza      15360.50
The Spinach Pesto Pizza      15596.00
Name: Revenue, dtype: float64

### Top 5 pizza types by quantity sold

In [108]:
Top_5_Pizza_Quantity = df_pizza_category.groupby("name")["quantity"].sum().sort_values(ascending=False).head(5)
Top_5_Pizza_Quantity

name
The Classic Deluxe Pizza      2453
The Barbecue Chicken Pizza    2432
The Hawaiian Pizza            2422
The Pepperoni Pizza           2418
The Thai Chicken Pizza        2371
Name: quantity, dtype: int64

### Revenue by Month

In [112]:
df_order_pizza = pd.merge(df_orders, df_pizza_category, on="order_id", how="outer")

df_order_pizza.head()

,order_id,date,time,pizza_type_id,name,category,ingredients,pizza_id,size,price,order_details_id,quantity,Revenue
0,1,2015-01-01,11:38:36,hawaiian,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",hawaiian_m,M,13.25,1,1,13.25
1,2,2015-01-01,11:57:40,classic_dlx,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",classic_dlx_m,M,16.00,2,1,16.00
2,2,2015-01-01,11:57:40,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",five_cheese_l,L,18.50,3,1,18.50
3,2,2015-01-01,11:57:40,ital_supr,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",ital_supr_l,L,20.75,4,1,20.75
4,2,2015-01-01,11:57:40,mexicana,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",mexicana_m,M,16.00,5,1,16.00

In [114]:
df_order_pizza["Month"] = df_order_pizza["date"].dt.to_period("M")

df_order_pizza.head(5)

,order_id,date,time,pizza_type_id,name,category,ingredients,pizza_id,size,price,order_details_id,quantity,Revenue,Month
0,1,2015-01-01,11:38:36,hawaiian,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",hawaiian_m,M,13.25,1,1,13.25,2015-01
1,2,2015-01-01,11:57:40,classic_dlx,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",classic_dlx_m,M,16.00,2,1,16.00,2015-01
2,2,2015-01-01,11:57:40,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",five_cheese_l,L,18.50,3,1,18.50,2015-01
3,2,2015-01-01,11:57:40,ital_supr,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",ital_supr_l,L,20.75,4,1,20.75,2015-01
4,2,2015-01-01,11:57:40,mexicana,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",mexicana_m,M,16.00,5,1,16.00,2015-01

In [124]:
Monthly_Revenue = df_order_pizza.groupby("Month")["Revenue"].sum()
Monthly_Revenue

Month
2015-01    69793.30
2015-02    65159.60
2015-03    70397.10
2015-04    68736.80
2015-05    71402.75
2015-06    68230.20
2015-07    72557.90
2015-08    68278.25
2015-09    64180.05
2015-10    64027.60
2015-11    70395.35
2015-12    64701.15
Freq: M, Name: Revenue, dtype: float64

### Monthly revenue growth

In [125]:
Monthly_Changed_Revenue = Monthly_Revenue.diff()
Monthly_Changed_Revenue

Month
2015-01        NaN
2015-02   -4633.70
2015-03    5237.50
2015-04   -1660.30
2015-05    2665.95
2015-06   -3172.55
2015-07    4327.70
2015-08   -4279.65
2015-09   -4098.20
2015-10    -152.45
2015-11    6367.75
2015-12   -5694.20
Freq: M, Name: Revenue, dtype: float64

In [126]:
Monthly_Growth_Revenue = Monthly_Revenue.pct_change() * 100
Monthly_Growth_Revenue

Month
2015-01         NaN
2015-02   -6.639176
2015-03    8.037956
2015-04   -2.358478
2015-05    3.878490
2015-06   -4.443176
2015-07    6.342792
2015-08   -5.898255
2015-09   -6.002204
2015-10   -0.237535
2015-11    9.945320
2015-12   -8.088887
Freq: M, Name: Revenue, dtype: float64

### Busiest month by order count

In [142]:
Order_Count_BYMonth =  df_order_pizza.groupby("Month")["order_id"].nunique()
Order_Count_BYMonth

Month
2015-01    1845
2015-02    1685
2015-03    1840
2015-04    1799
2015-05    1853
2015-06    1773
2015-07    1935
2015-08    1841
2015-09    1661
2015-10    1646
2015-11    1792
2015-12    1680
Freq: M, Name: order_id, dtype: int64

### Popular pizza Size by category

In [183]:
Popular_Size_byCategory = df_order_pizza.groupby(["category", "size"])["quantity"].sum()
Popular_Size_byCategory

category  size
Chicken   L       4932
          M       3894
          S       2224
Classic   L       4057
          M       4112
          S       6139
          XL       552
          XXL       28
Supreme   L       4564
          M       4046
          S       3377
Veggie    L       5403
          M       3583
          S       2663
Name: quantity, dtype: int64

### AOV by Month

In [154]:
AOV_Month = Monthly_Revenue / Order_Count_BYMonth
AOV_Month

Month
2015-01    37.828347
2015-02    38.670386
2015-03    38.259293
2015-04    38.208338
2015-05    38.533594
2015-06    38.482910
2015-07    37.497623
2015-08    37.087588
2015-09    38.639404
2015-10    38.898906
2015-11    39.283119
2015-12    38.512589
Freq: M, dtype: float64

### Pizza category contributes to total revenue

In [157]:
Category_Contribution_Revenue = Category_Revenue / Total_Revenue * 100
Category_Contribution_Revenue

category
Chicken    23.955138
Classic    26.905960
Supreme    25.456311
Veggie     23.682591
Name: Revenue, dtype: float64

### Weekdays VS Weekend Sales

In [173]:
df_order_pizza["days_of_week"] = df_order_pizza["date"].dt.dayofweek.apply(
    lambda x: "Weekend" if x >= 5 else "Weekday"
)

df_order_pizza.head()

,order_id,date,time,pizza_type_id,name,category,ingredients,pizza_id,size,price,order_details_id,quantity,Revenue,Month,days_of_week
0,1,2015-01-01,11:38:36,hawaiian,The Hawaiian Pizza,Classic,"Sliced Ham, Pineapple, Mozzarella Cheese",hawaiian_m,M,13.25,1,1,13.25,2015-01,Weekday
1,2,2015-01-01,11:57:40,classic_dlx,The Classic Deluxe Pizza,Classic,"Pepperoni, Mushrooms, Red Onions, Red Peppers,...",classic_dlx_m,M,16.00,2,1,16.00,2015-01,Weekday
2,2,2015-01-01,11:57:40,five_cheese,The Five Cheese Pizza,Veggie,"Mozzarella Cheese, Provolone Cheese, Smoked Go...",five_cheese_l,L,18.50,3,1,18.50,2015-01,Weekday
3,2,2015-01-01,11:57:40,ital_supr,The Italian Supreme Pizza,Supreme,"Calabrese Salami, Capocollo, Tomatoes, Red Oni...",ital_supr_l,L,20.75,4,1,20.75,2015-01,Weekday
4,2,2015-01-01,11:57:40,mexicana,The Mexicana Pizza,Veggie,"Tomatoes, Red Peppers, Jalapeno Peppers, Red O...",mexicana_m,M,16.00,5,1,16.00,2015-01,Weekday

In [172]:
Quantity_By_Days_of_Week = df_order_pizza.groupby("days_of_week")["quantity"].sum()
Quantity_By_Days_of_Week

days_of_week
Weekday    36046
Weekend    13528
Name: quantity, dtype: int64

### Average daily sales by day type

In [ ]:
(
    df_pizza_category.groupby("category")["Revenue"].sum()
    / df_pizza_category.groupby("category")["quantity"].sum()
)

In [189]:
Average_Daily_Sales = df_order_pizza.groupby(["date", "days_of_week"])["quantity"].sum().groupby("days_of_week").mean()
Average_Daily_Sales

days_of_week
Weekday    141.913386
Weekend    130.076923
Name: quantity, dtype: float64

# Insights:

1. Lowest Month by Revenue is October it also has the lowest orders. so we could try some offers during this month.

2. Classic made the most revenue and sold the most pizza, while Veggie made the least revenue. Chicken had the fewest pizzas sold.

3. Even though Chicken sold the least pizza it was the highest pizza sold in every category while Veggie was the least category what sold pizza and also made the least revenue.

4. We can give combo offers on Veggies Pizza and see if customers give good response on Sales as well as on revenues.